name: TodoApi

on:
  push:
    branches: [master]
    paths:
    - 'TodoApi/**'
  pull_request:
    branches: [master]
    paths:
    - 'TodoApi/**'

defaults:
  run:
    working-directory: TodoApi

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./output

    - name: Deploy to Production
      if: github.event_name == 'push'
      uses: azure/webapps-deploy@v2
      with:
        app-name: deltav-todo
        package: ./TodoApi/output
        publish-profile: ${{ secrets.AZURE_PUBLISH_401D1_TODO }}

    - name: Deploy to Alpha
      if: github.event_name == 'pull_request'
      uses: azure/webapps-deploy@v2
      with:
        app-name: deltav-todo
        package: ./TodoApi/output
        publish-profile: ${{ secrets.AZURE_PUBLISH_401D1_TODO_ALPHA }}
        slot-name: alpha
